platform = 'x11'
tools = False
target = 'release'
arch = 'x64'
bits = 64
optimize = 'speed'
production = True
use_lto = True
debug_symbols = False

gdscript = True
minizip = True
#custom_modules = 
disable_3d = False
disable_advanced_gui = False
pulseaudio = True
udev = True # I guess? idk
touch = True # Sure?

module_bmp_enabled = True or True
module_bullet_enabled = False # We use Rapier
module_camera_enabled = True
module_csg_enabled = False or True
module_cvtt_enabled = True
module_dds_enabled = True
module_denoise_enabled = True
module_enet_enabled = True
module_etc_enabled = True
module_fbx_enabled = True
module_freetype_enabled = True
module_gdnative_enabled = True
module_gdscript_enabled = True
module_gridmap_enabled = False
module_hdr_enabled = True
module_jpg_enabled = True
module_jsonrpc_enabled = True # TODO do we need it?
module_lightmapper_cpu_enabled = False
module_mbedtls_enabled = False # We don't use TLS atm
module_minimp3_enabled = True
module_mobile_vr_enabled = False
module_mono_enabled = False
module_ogg_enabled = True
module_opensimplex_enabled = True # TODO verify we're actually using it
module_opus_enabled = True
module_pluggable_physics_enabled = True
module_pvr_enabled = True
module_raycast_enabled = True
module_recast_enabled = True # TODO
module_regex_enabled = True # We don't use it, but RichTextLabel does.
module_squish_enabled = True
module_stb_vorbis_enabled = True
module_svg_enabled = True
module_tga_enabled = True
module_theora_enabled = True
module_tinyexr_enabled = True
module_upnp_enabled = True
module_vhacd_enabled = False # We don't need this for release builds.
module_visual_script_enabled = False
module_vorbis_enabled = True
module_webm_enabled = False or True
module_webp_enabled = False or True
module_webrtc_enabled = False
module_websocket_enabled = False
module_webxr_enabled = False or True
module_xatlas_unwrap_enabled = True
