assets:
  - asset: addons/arrow.png
    author: oglsdl
    source: https://opengameart.org/content/glow-arrow
    license: cc0
  - asset: addons/crosshairs
    author: LoneCoder
    source: https://opengameart.org/content/64-crosshairs-pack-split
    license: cc0
  - asset: addons/tiles/wall_decals
    author: yughues
    source: https://opengameart.org/content/free-decals-01-sci-fi
    license: cc0
  - asset: addons/tiles/grass/grass_0.png
    author: Lamoot
    source: https://opengameart.org/content/grass-001
    license: cc-by 3.0
  - asset: addons/weapons/cannon_reviewed.escn
    author: nazzyc
    source: https://opengameart.org/content/turret-reviwed
    license: cc-by 3.0
  - asset: addons/ores/Minirals.escn
    author: Tech Knight
    source: https://opengameart.org/content/4-minerals
    license: cc0
  - asset: addons/tiles/water/water_*.jpg
    author: Catalin Pavel
    source: https://opengameart.org/content/water-texture-pack
    license: cc0
  - asset: addons/tiles/sand/..
    author: jordonbc
    source: https://opengameart.org/content/close-up-sand-grains
    license: cc-by 4.0
  - asset: addons/map_detail/grass
    author: yughues
    source: https://opengameart.org/content/grass-pack-01
    license: cc0
  - asset: addons/weapons/muzzle_flashes
    source: http://www.jeanmoreno.com/unity/warfx/
    license: null
